### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation referenced only in Debug config

### ISSUE THREAD

**Issue by claq2** [NetCoreTemplates/razor#1]
https://github.com/NetCoreTemplates/razor/blob/632c210e08042f046fa2316301e22efb870d12f0/MyApp/MyApp.csproj#L18

Is this on purpose? When you switch to build in Release you get an error in MyApp's Startup.cs because it can't find AddRazorRuntimeCompilation(). If it is on purpose, what are you supposed to do when publishing in release mode? (I worked around it by removing the condition in the csproj file.)

**Comment by mythz** [comment]
Yeah it was a copy/paste misconfiguration. Typically for MVC this would only be [needed during development](https://github.com/NetCoreTemplates/mvc/blob/master/MyApp/Startup.cs#L22-L26) but is always required for ServiceStack.Razor controller-less pretty URLs + [Paged Based Routing](https://docs.servicestack.net/netcore-razor#page-based-routing-in-razor).

So I've removed the condition in this commit https://github.com/NetCoreTemplates/razor/commit/2b67c228f7f383749024725697b517b94482f096
